# Generated by Django 5.2 on 2025-05-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructor_learner_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='intrested_categories',
            new_name='interested_categories',
        ),
    ]
